version = 1

[[annotations]]
path = [
    "Tests/SpeziAccessGuardTests/__Snapshots__/**"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"